name: ServerCore
version: 1.0
main: com.arhenniuss.servercore.ServerCore
api-version: 1.20
author: Arhenniuss
description: Core systems plugin.

commands:
  servercore:
    description: ServerCore admin commands
    usage: /servercore <setassigner|reset|debug|reload>
    permission: servercore.admin
  dummy:
    description: Spawn or remove a training dummy
    usage: /dummy [remove]
    permission: servercore.dummy

permissions:
  servercore.admin:
    description: Allows access to ServerCore admin commands
    default: op
  servercore.dummy:
    description: Allows spawning training dummies
    default: op